select
    referral_id::varchar as source_referral_id,
    'ONEMIND|' || referral_id::varchar as referral_bk,
    sha2('ONEMIND|' || referral_id::varchar,256) as referral_hk,
    sha2('ONEMIND|' || client_id::varchar,256) as client_hk,
    iff(service_id is null, null, sha2('ONEMIND|' || service_id::varchar,256)) as service_hk,
    iff(referring_org_id is null, null, sha2('ONEMIND|' || referring_org_id::varchar,256)) as referring_organisation_hk,
    client_id::varchar as client_id,
    service_id::varchar as service_id,
    referring_org_id::varchar as referring_org_id,
    referral_received_at,
    referral_source,
    referred_by_name,
    presenting_problem,
    risk_level_at_referral,
    priority,
    referral_status,
    created_at::timestamp_ntz as source_created_at,
    updated_at::timestamp_ntz as source_updated_at,
    'ONEMIND' as record_source,
    current_timestamp()::timestamp_ntz as dbt_loaded_at,
    sha2(concat_ws('|',coalesce(referral_received_at::varchar,''),coalesce(referral_source::varchar,''),coalesce(referred_by_name::varchar,''),coalesce(presenting_problem::varchar,''),coalesce(risk_level_at_referral::varchar,''),coalesce(priority::varchar,''),coalesce(referral_status::varchar,'')),256) as referral_hashdiff,
    sha2(concat_ws('|',sha2('ONEMIND|' || client_id::varchar,256),sha2('ONEMIND|' || referral_id::varchar,256)),256) as client_referral_lk,
    sha2(concat_ws('|',sha2('ONEMIND|' || referral_id::varchar,256),iff(service_id is null, null, sha2('ONEMIND|' || service_id::varchar,256))),256) as referral_service_lk,
    sha2(concat_ws('|',sha2('ONEMIND|' || referral_id::varchar,256),iff(referring_org_id is null, null, sha2('ONEMIND|' || referring_org_id::varchar,256))),256) as referral_organisation_lk
from {{ source('onemind_raw', 'onemind_referrals') }}
