select
    session_id::varchar as source_session_id,
    'ONEMIND|' || session_id::varchar as session_bk,
    sha2('ONEMIND|' || session_id::varchar,256) as session_hk,
    sha2('ONEMIND|' || episode_id::varchar,256) as episode_hk,
    iff(clinician_id is null, null, sha2('ONEMIND|' || clinician_id::varchar,256)) as clinician_hk,
    iff(location_id is null, null, sha2('ONEMIND|' || location_id::varchar,256)) as location_hk,
    episode_id::varchar as episode_id,
    clinician_id::varchar as clinician_id,
    location_id::varchar as location_id,
    session_start_at,
    session_end_at,
    datediff('minute',session_start_at,session_end_at) as duration_minutes,
    session_type,
    delivery_channel,
    attendance_status,
    cancellation_reason,
    clinical_notes_entered,
    created_at::timestamp_ntz as source_created_at,
    updated_at::timestamp_ntz as source_updated_at,
    'ONEMIND' as record_source,
    current_timestamp()::timestamp_ntz as dbt_loaded_at,
    sha2(concat_ws('|',coalesce(session_start_at::varchar,''),coalesce(session_end_at::varchar,''),coalesce(session_type::varchar,''),coalesce(delivery_channel::varchar,''),coalesce(attendance_status::varchar,''),coalesce(cancellation_reason::varchar,''),coalesce(clinical_notes_entered::varchar,'')),256) as session_hashdiff,
    sha2(concat_ws('|',sha2('ONEMIND|' || episode_id::varchar,256),sha2('ONEMIND|' || session_id::varchar,256)),256) as episode_session_lk,
    sha2(concat_ws('|',sha2('ONEMIND|' || session_id::varchar,256),iff(clinician_id is null, null, sha2('ONEMIND|' || clinician_id::varchar,256))),256) as session_clinician_lk,
    sha2(concat_ws('|',sha2('ONEMIND|' || session_id::varchar,256),iff(location_id is null, null, sha2('ONEMIND|' || location_id::varchar,256))),256) as session_location_lk
from {{ source('onemind_raw', 'onemind_sessions') }}
