select
    assessment_id::varchar as source_assessment_id,
    'ONEMIND|' || assessment_id::varchar as assessment_bk,
    sha2('ONEMIND|' || assessment_id::varchar,256) as assessment_hk,
    sha2('ONEMIND|' || referral_id::varchar,256) as referral_hk,
    iff(assessor_clinician_id is null, null, sha2('ONEMIND|' || assessor_clinician_id::varchar,256)) as clinician_hk,
    iff(recommended_service_id is null, null, sha2('ONEMIND|' || recommended_service_id::varchar,256)) as recommended_service_hk,
    referral_id::varchar as referral_id,
    assessor_clinician_id::varchar as assessor_clinician_id,
    assessment_at,
    assessment_type,
    clinical_summary,
    recommended_service_id::varchar as recommended_service_id,
    accepted_for_treatment,
    created_at::timestamp_ntz as source_created_at,
    updated_at::timestamp_ntz as source_updated_at,
    'ONEMIND' as record_source,
    current_timestamp()::timestamp_ntz as dbt_loaded_at,
    sha2(concat_ws('|',coalesce(assessment_at::varchar,''),coalesce(assessment_type::varchar,''),coalesce(clinical_summary::varchar,''),coalesce(accepted_for_treatment::varchar,'')),256) as assessment_hashdiff,
    sha2(concat_ws('|',sha2('ONEMIND|' || referral_id::varchar,256),sha2('ONEMIND|' || assessment_id::varchar,256)),256) as referral_assessment_lk,
    sha2(concat_ws('|',sha2('ONEMIND|' || assessment_id::varchar,256),iff(assessor_clinician_id is null, null, sha2('ONEMIND|' || assessor_clinician_id::varchar,256))),256) as assessment_clinician_lk,
    sha2(concat_ws('|',sha2('ONEMIND|' || assessment_id::varchar,256),iff(recommended_service_id is null, null, sha2('ONEMIND|' || recommended_service_id::varchar,256))),256) as assessment_service_lk
from {{ source('onemind_raw', 'onemind_assessments') }}
