select
    clinician_id::varchar as source_clinician_id,
    'ONEMIND|' || clinician_id::varchar as clinician_bk,
    sha2('ONEMIND|' || clinician_id::varchar,256) as clinician_hk,
    staff_number,
    first_name,
    last_name,
    professional_role,
    registration_body,
    registration_number,
    team_id::varchar as team_id,
    base_location_id::varchar as base_location_id,
    employment_type,
    start_date,
    leaving_date,
    created_at::timestamp_ntz as source_created_at,
    updated_at::timestamp_ntz as source_updated_at,
    'ONEMIND' as record_source,
    current_timestamp()::timestamp_ntz as dbt_loaded_at,
    sha2(concat_ws('|',coalesce(staff_number::varchar,''),coalesce(first_name::varchar,''),coalesce(last_name::varchar,''),coalesce(professional_role::varchar,''),coalesce(registration_body::varchar,''),coalesce(registration_number::varchar,''),coalesce(employment_type::varchar,''),coalesce(start_date::varchar,''),coalesce(leaving_date::varchar,'')),256) as clinician_hashdiff,
    iff(team_id is null, null, sha2('ONEMIND|' || team_id::varchar,256)) as team_hk,
    iff(base_location_id is null, null, sha2('ONEMIND|' || base_location_id::varchar,256)) as base_location_hk,
    sha2(concat_ws('|',sha2('ONEMIND|' || clinician_id::varchar,256),iff(team_id is null, null, sha2('ONEMIND|' || team_id::varchar,256))),256) as clinician_team_lk,
    sha2(concat_ws('|',sha2('ONEMIND|' || clinician_id::varchar,256),iff(base_location_id is null, null, sha2('ONEMIND|' || base_location_id::varchar,256))),256) as clinician_location_lk
from {{ source('onemind_raw', 'onemind_clinicians') }}
