-- ============================================================================
-- Book-aligned validation and reconciliation queries
-- ============================================================================

-- Source client counts
SELECT 'RAW_ONEMIND_CLIENTS' AS DATASET, COUNT(*) AS ROW_COUNT
FROM ONEMIND_RAW_DB.PUBLIC.ONEMIND_CLIENTS
UNION ALL
SELECT 'RAW_BRIGHTPATH_CLIENTS', COUNT(*)
FROM ONEMIND_RAW_DB.PUBLIC.BRIGHTPATH_CLIENTS;

-- Staging client counts
SELECT 'STG_ONEMIND_CLIENTS' AS DATASET, COUNT(*) AS ROW_COUNT
FROM ONEMIND_ENT_DW.STAGING.STG_ONEMIND__CLIENTS
UNION ALL
SELECT 'STG_BRIGHTPATH_CLIENTS', COUNT(*)
FROM ONEMIND_ENT_DW.STAGING.STG_BRIGHTPATH__CLIENTS;

-- Vault/master/dimension client counts
SELECT 'HUB_CLIENT' AS DATASET, COUNT(*) AS ROW_COUNT
FROM ONEMIND_ENT_DW.RAW_VAULT.HUB_CLIENT
UNION ALL
SELECT 'HUB_MASTER_CLIENT', COUNT(*)
FROM ONEMIND_ENT_DW.BUSINESS_VAULT.HUB_MASTER_CLIENT
UNION ALL
SELECT 'DIM_CLIENT', COUNT(*)
FROM ONEMIND_DIM_DW.CORE.DIM_CLIENT;

-- Deterministic match counts by rule
SELECT MATCH_RULE, MATCH_SCORE, COUNT(*) AS MATCH_COUNT
FROM ONEMIND_ENT_DW.BUSINESS_VAULT.BV_CLIENT_DETERMINISTIC_MATCH
GROUP BY MATCH_RULE, MATCH_SCORE
ORDER BY MATCH_SCORE DESC;

-- Only deterministic matching is used in this version.
SELECT MATCH_METHOD, MATCH_RULE, COUNT(*) AS MATCH_COUNT
FROM ONEMIND_ENT_DW.BUSINESS_VAULT.BV_CLIENT_MATCH
GROUP BY MATCH_METHOD, MATCH_RULE
ORDER BY MATCH_RULE;

-- Every source identity should have exactly one master assignment.
SELECT CLIENT_HK, COUNT(*) AS ASSIGNMENT_COUNT
FROM ONEMIND_ENT_DW.BUSINESS_VAULT.BV_MASTER_CLIENT_ASSIGNMENT
GROUP BY CLIENT_HK
HAVING COUNT(*) <> 1;

-- One dimension row per master identity.
SELECT MASTER_CLIENT_HK, COUNT(*) AS DIMENSION_ROWS
FROM ONEMIND_DIM_DW.CORE.DIM_CLIENT
GROUP BY MASTER_CLIENT_HK
HAVING COUNT(*) <> 1;

-- Cross-source mastered clients.
SELECT *
FROM ONEMIND_DIM_DW.CORE.DIM_CLIENT
WHERE SOURCE_SYSTEM_COUNT = 2
ORDER BY CLIENT_KEY
LIMIT 100;

-- Client journey bridge coverage.
SELECT
    COUNT(DISTINCT MASTER_CLIENT_HK) AS MASTER_CLIENTS,
    COUNT(DISTINCT REFERRAL_HK) AS REFERRALS,
    COUNT(DISTINCT EPISODE_HK) AS EPISODES,
    COUNT(DISTINCT SESSION_HK) AS SESSIONS
FROM ONEMIND_ENT_DW.BUSINESS_VAULT.BRIDGE_CLIENT_JOURNEY;

-- Dimensional fact counts.
SELECT 'FACT_REFERRAL' AS DATASET, COUNT(*) AS ROW_COUNT FROM ONEMIND_DIM_DW.CORE.FACT_REFERRAL
UNION ALL SELECT 'FACT_ASSESSMENT', COUNT(*) FROM ONEMIND_DIM_DW.CORE.FACT_ASSESSMENT
UNION ALL SELECT 'FACT_SESSION', COUNT(*) FROM ONEMIND_DIM_DW.CORE.FACT_SESSION
UNION ALL SELECT 'FACT_OUTCOME', COUNT(*) FROM ONEMIND_DIM_DW.CORE.FACT_OUTCOME
UNION ALL SELECT 'FACT_RISK_ASSESSMENT', COUNT(*) FROM ONEMIND_DIM_DW.CORE.FACT_RISK_ASSESSMENT
UNION ALL SELECT 'FACT_GOAL', COUNT(*) FROM ONEMIND_DIM_DW.CORE.FACT_GOAL;
