-- ============================================================================
-- Validation and reconciliation queries
-- ============================================================================

-- Source counts
SELECT 'RAW_ONEMIND' AS DATASET, COUNT(*) AS ROW_COUNT
FROM ONEMIND_RAW_DB.PUBLIC.ONEMIND_CLIENTS
UNION ALL
SELECT 'RAW_BRIGHTPATH', COUNT(*)
FROM ONEMIND_RAW_DB.PUBLIC.BRIGHTPATH_CLIENTS;

-- Staging counts
SELECT 'STG_ONEMIND' AS DATASET, COUNT(*) AS ROW_COUNT
FROM ONEMIND_ENT_DW.STAGING.STG_ONEMIND__CLIENTS
UNION ALL
SELECT 'STG_BRIGHTPATH', COUNT(*)
FROM ONEMIND_ENT_DW.STAGING.STG_BRIGHTPATH__CLIENTS;

-- Vault and dimension counts
SELECT 'HUB_CLIENT' AS DATASET, COUNT(*) AS ROW_COUNT
FROM ONEMIND_ENT_DW.RAW_VAULT.HUB_CLIENT
UNION ALL
SELECT 'HUB_MASTER_CLIENT', COUNT(*)
FROM ONEMIND_ENT_DW.RAW_VAULT.HUB_MASTER_CLIENT
UNION ALL
SELECT 'DIM_CLIENT', COUNT(*)
FROM ONEMIND_DIM_DW.CORE.DIM_CLIENT;

-- Match counts by rule
SELECT
    MATCH_RULE,
    MATCH_SCORE,
    COUNT(*) AS MATCH_COUNT
FROM ONEMIND_ENT_DW.BUSINESS_VAULT.BV_CLIENT_MATCH
GROUP BY MATCH_RULE, MATCH_SCORE
ORDER BY MATCH_SCORE DESC;

-- Verify each source identity has one master assignment
SELECT
    CLIENT_HK,
    COUNT(*) AS ASSIGNMENT_COUNT
FROM ONEMIND_ENT_DW.BUSINESS_VAULT.BV_MASTER_CLIENT_ASSIGNMENT
GROUP BY CLIENT_HK
HAVING COUNT(*) <> 1;

-- Verify one dimension row per master identity
SELECT
    MASTER_CLIENT_HK,
    COUNT(*) AS DIMENSION_ROWS
FROM ONEMIND_DIM_DW.CORE.DIM_CLIENT
GROUP BY MASTER_CLIENT_HK
HAVING COUNT(*) <> 1;

-- Inspect mastered cross-source clients
SELECT *
FROM ONEMIND_DIM_DW.CORE.DIM_CLIENT
WHERE SOURCE_SYSTEM_COUNT = 2
ORDER BY CLIENT_KEY
LIMIT 100;

-- Inspect semantic output
SELECT *
FROM ONEMIND_DIM_DW.SEMANTIC.CLIENT
LIMIT 100;

-- Fuzzy matching decision profile
SELECT
    FUZZY_MATCH_DECISION,
    COUNT(*) AS CANDIDATE_COUNT,
    MIN(FUZZY_MATCH_SCORE) AS MIN_SCORE,
    MAX(FUZZY_MATCH_SCORE) AS MAX_SCORE
FROM ONEMIND_ENT_DW.BUSINESS_VAULT.BV_CLIENT_FUZZY_SCORED
GROUP BY FUZZY_MATCH_DECISION
ORDER BY FUZZY_MATCH_DECISION;

-- Accepted matches by method
SELECT
    MATCH_METHOD,
    MATCH_RULE,
    COUNT(*) AS MATCH_COUNT
FROM ONEMIND_ENT_DW.BUSINESS_VAULT.BV_CLIENT_MATCH
GROUP BY MATCH_METHOD, MATCH_RULE
ORDER BY MATCH_METHOD, MATCH_RULE;

-- Manual review queue
SELECT *
FROM ONEMIND_ENT_DW.BUSINESS_VAULT.BV_CLIENT_REVIEW_QUEUE
ORDER BY FUZZY_MATCH_SCORE DESC
LIMIT 100;
