-- OneMind Power BI Snowflake Security Setup

USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS BI_WH
WAREHOUSE_SIZE='XSMALL'
AUTO_SUSPEND=60
AUTO_RESUME=TRUE
INITIALLY_SUSPENDED=TRUE
COMMENT='Warehouse for Power BI';

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS POWERBI_ROLE
COMMENT='Read-only role for Power BI semantic layer';

USE ROLE USERADMIN;

CREATE OR REPLACE USER SVC_POWERBI
DEFAULT_ROLE=POWERBI_ROLE
DEFAULT_WAREHOUSE=BI_WH
DEFAULT_NAMESPACE='ONEMIND_DIM_DW.SEMANTIC';

ALTER USER SVC_POWERBI
SET PASSWORD = 'StrongPa$$word13';

USE ROLE SECURITYADMIN;

GRANT ROLE POWERBI_ROLE TO USER SVC_POWERBI;

GRANT USAGE, OPERATE
ON WAREHOUSE BI_WH
TO ROLE POWERBI_ROLE;

GRANT USAGE
ON DATABASE ONEMIND_DIM_DW
TO ROLE POWERBI_ROLE;

GRANT USAGE
ON SCHEMA ONEMIND_DIM_DW.SEMANTIC
TO ROLE POWERBI_ROLE;

GRANT SELECT
ON ALL VIEWS
IN SCHEMA ONEMIND_DIM_DW.SEMANTIC
TO ROLE POWERBI_ROLE;

GRANT SELECT
ON FUTURE VIEWS
IN SCHEMA ONEMIND_DIM_DW.SEMANTIC
TO ROLE POWERBI_ROLE;

GRANT SELECT
ON ALL TABLES
IN SCHEMA ONEMIND_DIM_DW.SEMANTIC
TO ROLE POWERBI_ROLE;

GRANT SELECT
ON ALL VIEWS
IN SCHEMA ONEMIND_DIM_DW.SEMANTIC
TO ROLE POWERBI_ROLE;

GRANT SELECT
ON FUTURE TABLES
IN SCHEMA ONEMIND_DIM_DW.SEMANTIC
TO ROLE POWERBI_ROLE;

GRANT SELECT
ON FUTURE VIEWS
IN SCHEMA ONEMIND_DIM_DW.SEMANTIC
TO ROLE POWERBI_ROLE;

SHOW GRANTS TO ROLE POWERBI_ROLE;
SHOW USERS LIKE 'SVC_POWERBI';
SHOW WAREHOUSES LIKE 'BI_WH';

USE ROLE SECURITYADMIN;

GRANT ROLE POWERBI_ROLE
TO USER BGHEOCA;

SHOW VIEWS IN SCHEMA SEMANTIC;

select * from ONEMIND_DIM_DW.SEMANTIC.CLIENT;

-- Connection details:
-- Account: CPRCYYC-FB19926.snowflakecomputing.com
-- User: SVC_POWERBI
-- Password: StrongPa$$word13
-- Role: POWERBI_ROLE
-- Warehouse: BI_WH
-- Database: ONEMIND_DIM_DW
-- Schema: SEMANTIC


USE ROLE SECURITYADMIN;

-- Unlock the service account
ALTER USER SVC_POWERBI SET MINS_TO_UNLOCK = 0;

